services:
  - type: web
    name: portfolio-server
    env: node
    rootDir: server
    plan: free
    autoDeploy: true
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Optional, app degrades gracefully without DB
      - key: MONGO_URI
        value: ""
      - key: JWT_SECRET
        generateValue: true
      # Set this to your client URL after it deploys (e.g., https://your-client.onrender.com or Vercel domain)
      - key: FRONTEND_ORIGIN
        value: "http://localhost:5173"

  - type: static_site
    name: portfolio-client
    rootDir: client
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      # After server deploys, set this to https://<server-domain>/api
      - key: VITE_API_BASE_URL
        value: "/api"
