services:
  - type: web
    name: portfolio-server
    env: node
    rootDir: server
    plan: free
    autoDeploy: true
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Optional, app degrades gracefully without DB
      - key: MONGO_URI
        value: ""
      - key: JWT_SECRET
        generateValue: true
      # Update after client is deployed to the actual static site domain (comma-separated allowed)
      - key: FRONTEND_ORIGIN
        value: "https://your-client.onrender.com"

staticSites:
  - name: portfolio-client
    rootDir: client
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      # After server deploys, set this to https://<server-domain>/api
      - key: VITE_API_BASE_URL
        value: "/api"
